version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - maintidx
    - misspell
    - nakedret
    - prealloc
    - reassign
    - revive
    - staticcheck
    - unused
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: '^(G107|G204|G306):'
      - linters:
          - revive
        path: "internal/pkg/remote/util/.*.go$"
        text: "var-naming: avoid meaningless package names"
      - linters:
          - revive
        path: "pkg/build/types/.*.go$"
        text: "var-naming: avoid meaningless package names"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
