run:
  timeout: 3m
  skip-files:
    - "internal/pkg/util/user/cgo_lookup_unix.go"

linters:
  disable-all: true
  enable-all: false
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - decorder
    - dupl
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - maintidx
    - misspell
    - reassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  misspell:
    locale: US

issues:
  max-per-linter: 0
  max-same-issues: 0
